name: cv_website
description: A CV website built with Flutter Web
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^2.0.1

  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  media_source: ^1.3.0
  url_launcher: ^6.2.2
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/projects/
    - assets/projects/restorma/
    - assets/projects/restormadmin/
    - assets/projects/mypeopler/
    - assets/projects/hospitalcarepluspharmacy/
    - assets/projects/hospitalcarepluspatient/
    - assets/projects/hospitalcareplusdoctor/
    - assets/projects/algebrapos/
    - assets/projects/lmc/
    - assets/projects/lmcwardfive/
    - assets/projects/gd/
    - assets/projects/raktabandana/
    - assets/projects/conference/
